import ExcelJS from 'exceljs';
import {sale,units,paid,debt,routeStats} from './domain.mjs';
const dollars=v=>v/100;const sum=(xs,fn)=>xs.reduce((s,x)=>s+fn(x),0);const dt=d=>new Date(d+'T12:00:00Z');
const clock=x=>new Intl.DateTimeFormat('es-EC',{hour:'2-digit',minute:'2-digit',timeZone:'America/Guayaquil'}).format(new Date(x));
const currency='"$"#,##0.00;[Red]("$"#,##0.00)';
export function workbookFor(db,start,end){
 if(!start||!end||start>end)throw Error('Elige un rango de fechas válido.');
 const routes=db.routes.filter(r=>r.date>=start&&r.date<=end).sort((a,b)=>a.date.localeCompare(b.date));if(!routes.length)throw Error('No hay rutas en este período.');
 const visits=db.visits.filter(v=>v.date>=start&&v.date<=end).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));const receipts=db.receipts.filter(x=>x.date>=start&&x.date<=end);const expenses=db.expenses.filter(x=>x.date>=start&&x.date<=end);const w=new ExcelJS.Workbook();w.creator=db.settings.name;w.created=new Date();w.calcProperties.fullCalcOnLoad=true;
 const name=v=>v.shopName||db.shops.find(s=>s.id===v.shopId)?.name||'Tienda';const shop=id=>db.shops.find(s=>s.id===id)?.name||'Tienda';
 function sheet(title,columns,description){const s=w.addWorksheet(title,{properties:{defaultRowHeight:22},pageSetup:{paperSize:9,orientation:'landscape',fitToPage:true,fitToWidth:1,fitToHeight:0}});s.columns=columns.map(([header,width])=>({header,width}));s.mergeCells(1,1,1,columns.length);s.getCell(1,1).value=`QUINUA RUTA · ${title}`;s.getRow(1).height=34;s.getRow(1).font={name:'Calibri',size:20,bold:true,color:{argb:'FF163D33'}};s.mergeCells(2,1,2,columns.length);s.getCell(2,1).value=description||`${start} a ${end} · Responsable: ${db.settings.name} · Moneda: USD`;s.getRow(2).height=30;s.getRow(2).font={name:'Calibri',size:11,color:{argb:'FF62736C'}};s.getRow(4).values=columns.map(c=>c[0]);s.getRow(4).height=32;s.getRow(4).eachCell(c=>{c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF163D33'}};c.font={name:'Calibri',size:11,bold:true,color:{argb:'FFFFFFFF'}};c.alignment={vertical:'middle',wrapText:true};});s.views=[{state:'frozen',ySplit:4}];s.pageSetup.printTitlesRow='1:4';return s;}
 function row(s,values,money=[],dates=[]){const r=s.addRow(values);r.font={name:'Calibri',size:11};r.alignment={vertical:'middle',wrapText:true};r.height=32;r.eachCell(c=>{c.border={bottom:{style:'hair',color:{argb:'FFE0E7E2'}}};if(r.number%2)c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF3F6F4'}};});money.forEach(col=>r.getCell(col).numFmt=currency);dates.forEach(col=>r.getCell(col).numFmt='dd/mm/yyyy');return r;}
 function finish(s){if(s.rowCount>4)s.autoFilter={from:{row:4,column:1},to:{row:s.rowCount,column:s.columnCount}};}
 const summary=sheet('Resumen',[['Concepto',42],['Resultado',26]],`${start} a ${end} · ${db.settings.name} · USD · ${routes.some(r=>!r.closed)?'PROVISIONAL: hay rutas abiertas':'Rutas cerradas'}`);
 const detail=sheet('Visitas',[['Fecha',14],['Hora',12],['Tienda',28],['Sector',27],['Vendidas',13],['Cortesías',13],['Cambios',13],['Caducadas retiradas',18],['Precio unitario',17],['Venta',15],['Cobrado hasta fin del período',20],['Pendiente al fin del período',20],['Caducidad entrega',17],['Observaciones',45],['Fotos',10],['ID visita',39]]);
 const prices=sheet('Precios',[['Fecha',14],['Tienda',28],['Fundas',13],['Precio unitario',17],['Importe',16],['Motivo precio especial',35],['ID visita',39]]);
 for(const v of visits)for(const l of v.lines.filter(l=>l.qty)){const n=prices.rowCount+1;row(prices,[dt(v.date),name(v),l.qty,dollars(l.price),{formula:`C${n}*D${n}`,result:dollars(l.qty*l.price)},l.reason||'',v.id],[4,5],[1]);}
 const priceEnd=Math.max(prices.rowCount,5);
 for(const v of visits){const n=detail.rowCount+1;row(detail,[dt(v.date),clock(v.createdAt),name(v),v.shopAddress||'',units(v),v.gifts,v.replacements,v.expired,v.lines.filter(l=>l.qty).length===1?dollars(v.lines.find(l=>l.qty).price):'Varios / sin venta',{formula:`SUMIF('Precios'!G5:G${priceEnd},P${n},'Precios'!E5:E${priceEnd})`,result:dollars(sale(v))},dollars(paid(db,v.id,end)),{formula:`J${n}-K${n}`,result:dollars(debt(db,v,end))},v.expiry?dt(v.expiry):'',v.notes||'',v.photos.length,v.id],[9,10,11,12],[1,13]);}
 const inventory=sheet('Inventario',[['Fecha',14],['ID ruta',39],['Salida',12],['Recargas',13],['Vendidas',13],['Cortesías',13],['Nuevas por cambio',18],['Regreso esperado',18],['Regreso físico',17],['Diferencia nuevas',18],['Caducadas retiradas',19],['Caducadas físicas',19],['Diferencia caducadas',20],['Estado',17],['Nota de cierre',45]]);
 for(const r of routes){const s=routeStats(db,r),n=inventory.rowCount+1;row(inventory,[dt(r.date),r.id,r.initial,s.reload,s.sold,s.gifts,s.replacements,{formula:`C${n}+D${n}-E${n}-F${n}-G${n}`,result:s.expected},r.closed?r.actual:'',{formula:`IF(N${n}="Cerrada",I${n}-H${n},"")`,result:r.closed?r.actual-s.expected:''},s.expired,r.closed?r.actualExpired:'',{formula:`IF(N${n}="Cerrada",L${n}-K${n},"")`,result:r.closed?r.actualExpired-s.expired:''},r.closed?'Cerrada':'Abierta',r.note||''],[],[1]);}
 const finance=sheet('Contabilidad',[['Fecha',14],['ID ruta',39],['Venta',15],['Efectivo inicial',18],['Cobrado efectivo',19],['Cobrado transferencia',21],['Gastos efectivo',19],['Gastos transferencia',21],['Efectivo esperado',19],['Efectivo físico',19],['Diferencia efectivo',20],['Costo por funda',18],['Margen estimado',20],['Estado',16]]);
 for(const r of routes){const s=routeStats(db,r);const ec=sum(db.expenses.filter(x=>x.routeId===r.id&&x.method==='cash'),x=>x.amount);const et=sum(db.expenses.filter(x=>x.routeId===r.id&&x.method==='transfer'),x=>x.amount);const n=finance.rowCount+1;const marginal=r.cost===null?null:s.sales-(s.sold+s.gifts+s.replacements)*r.cost-s.expenses;row(finance,[dt(r.date),r.id,dollars(s.sales),dollars(r.openingCash),dollars(s.cash),dollars(s.transfer),dollars(ec),dollars(et),{formula:`D${n}+E${n}-G${n}`,result:dollars(s.cashExpected)},r.closed?dollars(r.actualCash):'',{formula:`IF(N${n}="Cerrada",J${n}-I${n},"")`,result:r.closed?dollars(r.actualCash-s.cashExpected):''},r.cost===null?'Sin costo':dollars(r.cost),marginal===null?'Sin costo':dollars(marginal),r.closed?'Cerrada':'Abierta'],[3,4,5,6,7,8,9,10,11,12,13],[1]);}
 const ledger=sheet('Movimientos',[['Fecha',14],['Hora',12],['Tipo',15],['Tienda / detalle',30],['Medio',18],['Ingreso',17],['Gasto',17],['Aplicado a entregas de este período',22],['Aplicado a otras entregas',22],['Referencia',40],['ID ruta',39],['ID movimiento',39]]);
 for(const x of [...receipts.map(x=>({...x,type:'Cobro'})),...expenses.map(x=>({...x,type:'Gasto'}))].sort((a,b)=>a.createdAt.localeCompare(b.createdAt))){const current=x.type==='Cobro'?sum(x.allocations.filter(a=>visits.some(v=>v.id===a.visitId)),a=>a.amount):0;row(ledger,[dt(x.date),clock(x.createdAt),x.type,x.type==='Cobro'?shop(x.shopId):x.description,x.method==='cash'?'Efectivo':'Transferencia',x.type==='Cobro'?dollars(x.amount):0,x.type==='Gasto'?dollars(x.amount):0,dollars(current),x.type==='Cobro'?dollars(x.amount-current):0,x.note||'',x.routeId,x.id],[6,7,8,9],[1]);}
 const evidence=sheet('Evidencias',[['Fecha',15],['Hora',12],['Tienda',29],['Detalle',36],['Fotografía',40]]);let photoCount=0;
 for(const v of visits){if(!v.photos.length){row(evidence,[dt(v.date),clock(v.createdAt),name(v),'Sin fotografía',''],[],[1]);continue;}v.photos.forEach((p,i)=>{const r=row(evidence,[dt(v.date),clock(v.createdAt),name(v),`Foto ${i+1} de ${v.photos.length}\n${v.notes||''}`,''],[],[1]);r.height=154;const pic=w.addImage({base64:p.data,extension:'jpeg'});const ratio=(p.width||4)/(p.height||3);const width=Math.min(260,180*ratio),height=width/ratio;evidence.addImage(pic,{tl:{col:4,row:r.number-1},ext:{width,height},editAs:'oneCell'});photoCount++;});}
 const dr=Math.max(detail.rowCount,5),ir=Math.max(inventory.rowCount,5),fr=Math.max(finance.rowCount,5),lr=Math.max(ledger.rowCount,5);const summaryRow=(label,value,cash=false)=>row(summary,[label,value],cash?[2]:[]);
 summaryRow('Rutas',routes.length);summaryRow('Visitas registradas',visits.length);summaryRow('Fotografías incluidas',photoCount);
 summaryRow('Fundas vendidas',{formula:`SUM('Visitas'!E5:E${dr})`,result:sum(visits,units)});
 summaryRow('Fundas de cortesía',{formula:`SUM('Visitas'!F5:F${dr})`,result:sum(visits,v=>v.gifts)});
 summaryRow('Nuevas entregadas por cambio',{formula:`SUM('Visitas'!G5:G${dr})`,result:sum(visits,v=>v.replacements)});
 summaryRow('Caducadas retiradas',{formula:`SUM('Visitas'!H5:H${dr})`,result:sum(visits,v=>v.expired)});
 summaryRow('Ventas nuevas del período',{formula:`SUM('Visitas'!J5:J${dr})`,result:dollars(sum(visits,sale))},true);
 summaryRow('Dinero recibido en el período',{formula:`SUM('Movimientos'!F5:F${lr})`,result:dollars(sum(receipts,r=>r.amount))},true);
 summaryRow('Cobros de otras entregas',{formula:`SUM('Movimientos'!I5:I${lr})`,result:dollars(sum(receipts,r=>sum(r.allocations.filter(a=>!visits.some(v=>v.id===a.visitId)),a=>a.amount)))},true);
 summaryRow('Pendiente de estas ventas al cierre del período',{formula:`SUM('Visitas'!L5:L${dr})`,result:dollars(sum(visits,v=>debt(db,v,end)))},true);
 summaryRow('Gastos del período',{formula:`SUM('Movimientos'!G5:G${lr})`,result:dollars(sum(expenses,e=>e.amount))},true);
 summaryRow('Diferencia de fundas (rutas cerradas)',{formula:`SUM('Inventario'!J5:J${ir})`,result:sum(routes.filter(r=>r.closed),r=>r.actual-routeStats(db,r).expected)});
 summaryRow('Diferencia de efectivo (rutas cerradas)',{formula:`SUM('Contabilidad'!K5:K${fr})`,result:dollars(sum(routes.filter(r=>r.closed),r=>r.actualCash-routeStats(db,r).cashExpected))},true);
 summaryRow('Estado del reporte',routes.some(r=>!r.closed)?'Provisional: hay rutas abiertas':'Completo: rutas cerradas');
 summaryRow('Margen estimado',routes.some(r=>r.cost===null)?'Configura costo antes de iniciar ruta':{formula:`SUM('Contabilidad'!M5:M${fr})`,result:dollars(sum(routes,r=>{const s=routeStats(db,r);return s.sales-(s.sold+s.gifts+s.replacements)*r.cost-s.expenses;}))},true);
 const note=summary.addRow(['Margen = ventas − costo de vendidas, cortesías y reposiciones − gastos. El costo de reposiciones representa la pérdida por cambio; las caducadas retiradas no se descuentan dos veces.']);summary.mergeCells(note.number,1,note.number,2);note.height=70;note.font={name:'Calibri',size:11,color:{argb:'FF62736C'}};note.alignment={wrapText:true,vertical:'middle'};
 const note2=summary.addRow(['Los saldos pendientes se calculan con los cobros registrados hasta la fecha final. El efectivo se concilia por ruta. Las diferencias positivas indican sobrante y las negativas, faltante.']);summary.mergeCells(note2.number,1,note2.number,2);note2.height=60;note2.alignment={wrapText:true,vertical:'middle'};note2.font={name:'Calibri',size:11,color:{argb:'FF62736C'}};
 [detail,prices,inventory,finance,ledger,evidence].forEach(finish);return w;
}
export async function makeExcel(db,start,end){const w=workbookFor(db,start,end);return new Blob([await w.xlsx.writeBuffer()],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});}
