import vm from 'node:vm';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const source=await fs.readFile('sw.js','utf8');assert.ok(!source.includes('__APP_VERSION__'));
for(const scope of ['/QuinuaRuta/','/']){const listeners={};let downloaded=[],deleted=[];const store=new Map(),key='';let available=false;const cache={addAll:async urls=>{downloaded=urls;for(const u of urls)store.set(u,{offline:true,url:u});},match:async req=>store.get(typeof req==='string'?req:req.url),put:async(url,response)=>store.set(url,response)};const context=vm.createContext({URL,Promise,caches:{open:async()=>cache,keys:async()=>[`quinua-ruta-${encodeURIComponent(scope)}-old`,`quinua-ruta-other-project-old`],delete:async k=>{deleted.push(k);return true;}},fetch:async request=>{if(!available)throw Error('offline');return {ok:true,redirected:false,headers:{get:()=> 'text/html'},clone:()=>({url:request.url,fromNetwork:true})};},self:{location:{href:`https://test.github.io${scope}sw.js`},clients:{claim:async()=>{}},skipWaiting:async()=>{},addEventListener:(name,callback)=>listeners[name]=callback}});vm.runInContext(source,context);
let work;listeners.install({waitUntil:p=>work=p});await work;assert.equal(downloaded.length,8);assert.equal(downloaded[0],`https://test.github.io${scope}`);assert.ok(downloaded.every(u=>u.startsWith(`https://test.github.io${scope}`)));
listeners.activate({waitUntil:p=>work=p});await work;assert.equal(deleted.length,1);assert.ok(!deleted[0].includes('other-project'));
let response;listeners.fetch({request:{url:`https://test.github.io${scope}`,method:'GET',mode:'navigate'},respondWith:p=>response=p,waitUntil:p=>work=p});assert.equal((await response).offline,true);
response=null;listeners.fetch({request:{url:`https://test.github.io${scope}app.js`,method:'GET',mode:'cors'},respondWith:p=>response=p});assert.equal((await response).offline,true);
if(scope!=='/'){response=null;listeners.fetch({request:{url:'https://test.github.io/Other/app.js',method:'GET',mode:'cors'},respondWith:p=>response=p});assert.equal(response,null);}}
const manifest=JSON.parse(await fs.readFile('manifest.webmanifest','utf8'));assert.equal(manifest.start_url,'./');assert.equal(manifest.scope,'./');const html=await fs.readFile('index.html','utf8');assert.ok(!/(?:href|src)="\//.test(html));
console.log('GitHub root and repository paths passed: local assets, scoped cache, offline navigation, manifest.');
