import test from 'node:test';import assert from 'node:assert/strict';
import {initial,integer,cents,sale,paid,debt,allocate,routeStats,validateVisit,validateDB} from './domain.mjs';import {workbookFor} from './report.mjs';
function fixture(){const db=initial();db.shops.push({id:'s',name:'Tienda Sol',address:'Cuenca',phone:'',notes:'',price:80});db.routes.push({id:'r',date:'2026-09-29',initial:120,openingCash:500,cost:40,createdAt:'2026-09-29T12:00:00Z',closed:false,reloads:[]});return db;}
function visit(id='v'){return {id,routeId:'r',shopId:'s',shopName:'Tienda Sol',shopAddress:'Cuenca',date:'2026-09-29',createdAt:'2026-09-29T13:00:00Z',lines:[{qty:10,price:80,reason:''},{qty:5,price:70,reason:'Acuerdo'}],gifts:2,replacements:3,expired:3,notes:'',expiry:'2026-10-03',photos:[]};}
test('Money is exact in cents, rejects invalid input',()=>{assert.equal(cents('0.80'),80);assert.equal(cents('0,70'),70);assert.equal(cents('9.60'),960);assert.throws(()=>cents('1.234'));assert.throws(()=>integer(-1));assert.throws(()=>integer(1.5));});
test('Mixed price sales, courtesy and replacement inventory',()=>{const db=fixture(),v=visit();validateVisit(db,v);db.visits.push(v);assert.equal(sale(v),1150);const s=routeStats(db,db.routes[0]);assert.equal(s.expected,100);assert.equal(s.sales,1150);assert.equal(s.expired,3);assert.throws(()=>validateVisit(db,{...visit('v2'),gifts:110}));});
test('Partial payments, old debt collection, cash and transfer remain separate',()=>{const db=fixture();const v=visit();db.visits.push(v);db.receipts.push({id:'c1',routeId:'r',date:v.date,createdAt:v.createdAt,shopId:'s',amount:500,method:'cash',allocations:[{visitId:'v',amount:500}]});assert.equal(debt(db,v),650);const alloc=allocate(db,'s',650);db.receipts.push({id:'c2',routeId:'r',date:v.date,createdAt:v.createdAt,shopId:'s',amount:650,method:'transfer',allocations:alloc});assert.equal(debt(db,v),0);assert.throws(()=>allocate(db,'s',1));const s=routeStats(db,db.routes[0]);assert.equal(s.cashExpected,1000);assert.equal(s.transfer,650);assert.equal(s.sales,1150);});
test('Historical period does not include future collections',()=>{const db=fixture(),v=visit();db.visits.push(v);db.routes.push({...db.routes[0],id:'r2',date:'2026-09-30',closed:true,actual:120,actualCash:500,actualExpired:0});db.routes[0].closed=true;db.routes[0].actual=100;db.routes[0].actualCash=500;db.routes[0].actualExpired=3;db.receipts.push({id:'c',routeId:'r2',date:'2026-09-30',createdAt:'2026-09-30T13:00:00Z',shopId:'s',amount:1150,method:'cash',allocations:[{visitId:'v',amount:1150}]});assert.equal(paid(db,'v','2026-09-29'),0);assert.equal(debt(db,v,'2026-09-29'),1150);assert.equal(debt(db,v),0);const w=workbookFor(db,'2026-09-29','2026-09-29');assert.equal(w.getWorksheet('Visitas').getCell('L5').value.result,11.5);const later=workbookFor(db,'2026-09-30','2026-09-30');assert.equal(later.getWorksheet('Movimientos').getCell('I5').value,11.5);});
test('Edits cannot reduce sales below receipts or exceed stock',()=>{const db=fixture(),v=visit();db.visits.push(v);db.receipts.push({id:'c',routeId:'r',date:v.date,createdAt:v.createdAt,shopId:'s',amount:1100,method:'cash',allocations:[{visitId:'v',amount:1100}]});assert.throws(()=>validateVisit(db,{...v,lines:[{qty:1,price:80}]},v.id));validateVisit(db,{...v,gifts:3},v.id);db.routes[0].closed=true;assert.throws(()=>validateVisit(db,v,v.id));});
test('Reloads and expenses reconcile, backup detects corrupt accounting',()=>{const db=fixture();db.routes[0].reloads.push({qty:20,createdAt:'2026-09-29T13:00:00Z',note:''});db.expenses.push({id:'e',routeId:'r',date:'2026-09-29',amount:250,method:'cash',createdAt:'2026-09-29T14:00:00Z',description:'Gasolina'});assert.equal(routeStats(db,db.routes[0]).expected,140);assert.equal(routeStats(db,db.routes[0]).cashExpected,250);validateDB(db);const bad=structuredClone(db);bad.expenses[0].amount=-1;assert.throws(()=>validateDB(bad));});
test('Excel includes all sheets, cached calculations and embedded JPEG',async()=>{const db=fixture(),v=visit();v.photos=[{data:'data:image/jpeg;base64,/9j/2Q==',width:400,height:300}];db.visits.push(v);Object.assign(db.routes[0],{closed:true,actual:99,actualExpired:3,actualCash:450});const w=workbookFor(db,'2026-09-29','2026-09-29');assert.deepEqual(w.worksheets.map(s=>s.name),['Resumen','Visitas','Precios','Inventario','Contabilidad','Movimientos','Evidencias']);assert.equal(w.getWorksheet('Precios').getCell('E5').value.result,8);assert.equal(w.getWorksheet('Precios').getCell('E6').value.result,3.5);assert.equal(w.getWorksheet('Visitas').getCell('J5').value.result,11.5);assert.equal(w.getWorksheet('Inventario').getCell('H5').value.result,100);assert.equal(w.getWorksheet('Inventario').getCell('J5').value.result,-1);assert.equal(w.getWorksheet('Contabilidad').getCell('K5').value.result,-.5);assert.equal(w.getWorksheet('Contabilidad').getCell('M5').value,3.5);assert.equal(w.getWorksheet('Evidencias').getImages().length,1);const buffer=await w.xlsx.writeBuffer();assert.ok(buffer.byteLength>10000);const loaded=new w.constructor();await loaded.xlsx.load(buffer);assert.equal(loaded.getWorksheet('Visitas').getCell('J5').value.result,11.5);assert.equal(loaded.getWorksheet('Evidencias').getImages().length,1);});
