import {JSDOM} from 'jsdom';import {indexedDB} from 'fake-indexeddb';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';
const html=await fs.readFile('index.html','utf8');const code=await fs.readFile('app.js','utf8');
const dom=new JSDOM(html,{url:'https://example.test/QuinuaRuta/',runScripts:'outside-only',pretendToBeVisual:true});const {window:w}=dom;Object.defineProperty(w,'indexedDB',{value:indexedDB});Object.defineProperty(w,'crypto',{value:webcrypto});w.structuredClone=structuredClone;w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.URL.createObjectURL=()=> 'blob:mock';w.URL.revokeObjectURL=()=>{};const originalClick=w.HTMLAnchorElement.prototype.click;w.HTMLAnchorElement.prototype.click=function(){if(this.href.startsWith('blob:'))return;return originalClick.call(this);};w.scrollTo=()=>{};
let gpsError=false;Object.defineProperty(w.navigator,'geolocation',{value:{getCurrentPosition:(ok,fail)=>gpsError?fail({code:1}):ok({coords:{latitude:-2.9,longitude:-79,accuracy:10}})}});
const markers=[];w.L={map:el=>{el.classList.add('leaflet-container');return {setView(){return this;},fitBounds(){},on(){return this;}};},tileLayer:()=>({addTo(){}}),divIcon:()=>({}),marker:(point,opts)=>{markers.push({point,opts});return {addTo(){return this;},bindPopup(html){markers.at(-1).popup=html;return this;},on(){return this;},setLatLng(){}};},circle:()=>({addTo(){}})};w.eval(code);
const pause=()=>new Promise(r=>setTimeout(r,40));const $=s=>w.document.querySelector(s);const click=async s=>{assert.ok($(s),`Missing ${s}`);$(s).click();await pause();};const input=(name,value)=>{const e=$(`.modal [name="${name}"]`);assert.ok(e,name);e.value=value;e.dispatchEvent(new w.Event('input',{bubbles:true}));};const submit=async()=>{const f=$('.modal form');assert.ok(f.checkValidity(),'Form invalid');f.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await pause();assert.ok(!$('.form-error')?.textContent,$('.form-error')?.textContent);};
await pause();assert.match($('#app').textContent,/Tu jornada/);assert.equal($('.startup-error'),null);
await click('[data-action="start-route"]');input('initial_sal','100');input('initial_chocolate','20');input('openingCash','5.00');await submit();assert.match($('#app').textContent,/Regreso esperado120/);
await click('[data-action="nav"][data-view="shops"]');await click('[data-action="shop"]');input('name','Tienda Sol');input('address','Cuenca');await submit();assert.match($('#app').textContent,/Tienda Sol/);
await click('[data-action="nav"][data-view="home"]');await click('[data-action="visit"]');const select=$('#visit-shop');select.value=select.options[1].value;select.dispatchEvent(new w.Event('change',{bubbles:true}));input('qty','10');input('gifts_sal','2');input('replacements_chocolate','3');input('expired_chocolate','3');await click('[data-action="full-payment"]');assert.equal($('[name="paid"]').value,'8.00');await submit();assert.match($('#app').textContent,/105 fundas/);
await click('[data-action="visit-detail"]');assert.match($('.modal').textContent,/8,00|8.00/);await click('[data-action="edit-visit"]');assert.equal($('#visit-shop').disabled,true);input('qty','15');await submit();assert.match($('#app').textContent,/100 fundas/);
await click('[data-action="nav"][data-view="finance"]');assert.match($('#app').textContent,/4,00|4.00/);await click('[data-action="receipt"]');input('amount','4.00');await submit();assert.match($('#app').textContent,/Todo al día/);
await click('[data-action="expense"]');input('description','Parqueo');input('amount','1.00');await submit();
await click('[data-action="nav"][data-view="route"]');await click('[data-action="close-route"]');for(const p of ['sal','dulce','chocolate','leche','galletas']){input('actual_'+p,p==='sal'?'83':p==='chocolate'?'17':'0');input('actualExpired_'+p,p==='chocolate'?'3':'0');}input('actualCash','16.00');await submit();assert.match($('#app').textContent,/Inventario cuadrado/);assert.match($('#app').textContent,/Efectivo cuadrado/);
// Add a second route with location-only customer creation and persisted map pin.
await click('[data-action="start-route"]');input('initial_sal','5');input('initial_dulce','5');await submit();await click('[data-action="nav"][data-view="home"]');await click('[data-action="visit-here"]');assert.match($('#visit-location').textContent,/Precisión aproximada: 10 m/);input('qty','2');input('pointName','Punto GPS');await submit();await click('[data-action="nav"][data-view="map"]');assert.match($('#app').textContent,/1 entregas con ubicación/);assert.ok(markers.some(m=>m.popup?.includes('Punto GPS')));await click('[data-action="visit-detail"]');assert.match($('.modal a[href*="google.com"]').href,/query=-2.9,-79/);await click('[data-action="modal-close"]');
gpsError=true;await click('[data-action="visit-here"]');assert.match($('#toast').textContent,/denegado/);input('qty','1');const form=$('.modal form');form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await pause();assert.match($('.form-error').textContent,/ubicación/);await click('[data-action="modal-close"]');
await click('[data-action="nav"][data-view="reports"]');await click('[data-action="excel"]');await pause();assert.match($('#toast').textContent,/Excel listo/);
let registered;Object.defineProperty(w.document,'modelContext',{value:{registerTool:tool=>registered=tool}}); // API unavailable at boot in this DOM; tools are feature-detected.
const t=indexedDB.open('quinua-ruta:/QuinuaRuta/',1);const loaded=await new Promise(resolve=>{t.onsuccess=()=>{const req=t.result.transaction('data').objectStore('data').get('main');req.onsuccess=()=>resolve(req.result);};});assert.equal(loaded.visits[0].lines[0].qty,15);assert.equal(loaded.routes[0].closed,true);assert.equal(loaded.receipts.length,2);assert.equal(loaded.expenses[0].amount,100);assert.equal(loaded.routes[0].actualCash,1600);assert.equal(loaded.routes[0].initialByType.chocolate,20);assert.equal(loaded.routes[0].actualByType.sal,83);assert.equal(loaded.visits[0].replacementsByType.chocolate,3);assert.equal(loaded.visits[1].location.lat,-2.9);assert.equal(loaded.visits[1].lines[0].productId,'sal');assert.equal(loaded.shops[1].name,'Punto GPS');
console.log('UI flow passed: start, shop, visit, full payment, edit, debt collection, expense, closure, Excel, persisted data.');dom.window.close();
